In [1]:
import pandas as pd
import dec1
import datetime
from epw import epw

In [2]:
meteo_df=pd.read_csv('/home/ict4bd/Residential/prova_meteo/notmod_epw/IOSLOOSL9_2019.epw',index_col='Date_Time',parse_dates=[0,])
meteo_df.head()

,Temperature_C,Dew_Point_C,Humidity,Wind,Speed_m/s,Gust_m/s,Pressure_Pa,Precip_Rate_mm,Precip_Accum_mm,UV,Solar_W/m2
Date_Time,,,,,,,,,,,
2019-01-01 00:00:00,4.722222,4.388889,98.0,202.5,6.258382,6.258382,99887.0,0.0,0.0,0,0.0
2019-01-01 00:10:00,4.833333,4.555556,98.0,180.0,5.364327,6.258382,99887.0,0.0,0.0,0,0.0
2019-01-01 00:20:00,5.333333,4.611111,95.0,180.0,5.364327,5.364327,99887.0,0.0,0.0,0,0.0
2019-01-01 00:30:00,6.222222,3.388889,82.0,180.0,5.364327,5.364327,99887.0,0.0,0.0,0,0.0
2019-01-01 00:40:00,6.500000,2.555556,76.0,180.0,5.364327,5.364327,99887.0,0.0,0.0,0,0.0

In [3]:
meteo=meteo_df.resample('H').mean().interpolate()
meteo.head()

,Temperature_C,Dew_Point_C,Humidity,Wind,Speed_m/s,Gust_m/s,Pressure_Pa,Precip_Rate_mm,Precip_Accum_mm,UV,Solar_W/m2
Date_Time,,,,,,,,,,,
2019-01-01 00:00:00,5.657407,3.648148,87.500000,183.75,5.513336,5.662345,99870.07,0.0,0.0,0.0,0.0
2019-01-01 01:00:00,6.416667,1.398148,70.333333,180.00,3.874236,4.172255,99751.56,0.0,0.0,0.0,0.0
2019-01-01 02:00:00,5.898148,-0.990741,61.333333,236.25,6.183877,6.183877,99683.84,0.0,0.0,0.0,0.0
2019-01-01 03:00:00,5.620370,-3.703704,51.166667,247.50,5.960364,6.109373,99599.19,0.0,0.0,0.0,0.0
2019-01-01 04:00:00,5.231481,-3.009259,55.333333,191.25,5.438832,5.513336,99446.82,0.0,0.0,0.0,0.0

In [4]:
meteo.columns
meteo

,Temperature_C,Dew_Point_C,Humidity,Wind,Speed_m/s,Gust_m/s,Pressure_Pa,Precip_Rate_mm,Precip_Accum_mm,UV,Solar_W/m2
Date_Time,,,,,,,,,,,
2019-01-01 00:00:00,5.657407,3.648148,87.500000,183.75,5.513336,5.662345,99870.07,0.0,0.0,0.0,0.0
2019-01-01 01:00:00,6.416667,1.398148,70.333333,180.00,3.874236,4.172255,99751.56,0.0,0.0,0.0,0.0
2019-01-01 02:00:00,5.898148,-0.990741,61.333333,236.25,6.183877,6.183877,99683.84,0.0,0.0,0.0,0.0
2019-01-01 03:00:00,5.620370,-3.703704,51.166667,247.50,5.960364,6.109373,99599.19,0.0,0.0,0.0,0.0
2019-01-01 04:00:00,5.231481,-3.009259,55.333333,191.25,5.438832,5.513336,99446.82,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
2019-12-31 19:00:00,3.120370,-9.916667,37.833333,142.50,2.086127,1.937118,102697.38,0.0,0.0,0.0,0.0
2019-12-31 20:00:00,2.981481,-9.768519,38.666667,180.00,2.458650,2.235136,102663.52,0.0,0.0,0.0,0.0
2019-12-31 21:00:00,2.703704,-9.574074,40.000000,187.50,1.490091,2.086127,102595.80,0.0,0.0,0.0,0.0
2019-12-31 22:00:00,3.333333,-9.222222,39.333333,150.00,2.309641,4.321264,102528.08,0.0,0.0,0.0,0.0
2019-12-31 23:00:00,2.814815,-9.305556,40.500000,71.25,1.266577,2.011623,102494.22,0.0,0.0,0.0,0.0

In [5]:
latitude = 59.912197  # latitude  N
longitude = 10.752936  # longitude E
elevation = 25  # meters above the sea

In [6]:
rad=pd.DataFrame(meteo['Solar_W/m2'].values,index=meteo.index,columns=['ghi'])

In [7]:
rad=dec1.main(rad,latitude,longitude,elevation)

/home/ict4bd/Residential/prova_meteo/dec1.py:244: RuntimeWarning: invalid value encountered in double_scalars
  df['k_b'] = df['dni']/df['dni_clear']
/home/ict4bd/Residential/prova_meteo/dec1.py:245: RuntimeWarning: invalid value encountered in double_scalars
  df['k_d'] = df['dhi']/df['dhi_clear']

In [8]:
data=epw()
data.read('NOR_Oslo.Fornebu.014880_IWEC.epw')

In [9]:
head=data.headers # this is a dictionary of the header information
print(head)

{'LOCATION': ['OSLO/FORNEBU', '-', 'NOR', 'IWEC Data', '014880', '59.90', '10.62', '1.0', '17.0'], 'DESIGN CONDITIONS': ['1', 'Climate Design Data 2009 ASHRAE Handbook', '', 'Heating', '1', '-17.2', '-14.5', '-19.9', '0.6', '-16', '-17', '0.8', '-12.9', '10.6', '5.4', '9.4', '4.2', '0.8', '0', 'Cooling', '7', '8.8', '26.8', '17.8', '25', '17', '23.2', '15.9', '19.2', '24.1', '18.2', '23.1', '17.1', '21.6', '3.2', '170', '17.7', '12.7', '20.6', '16.2', '11.5', '19.4', '15.2', '10.8', '18.5', '54.5', '23.7', '51.2', '23.1', '48.1', '21.3', '894', 'Extremes', '8.5', '7.3', '6.4', '24.3', '-18.7', '29.5', '4.2', '2.7', '-21.7', '31.4', '-24.2', '33', '-26.5', '34.5', '-29.6', '36.4'], 'TYPICAL/EXTREME PERIODS': ['6', 'Summer - Week Nearest Max Temperature For Period', 'Extreme', '7/27', '8/ 2', 'Summer - Week Nearest Average Temperature For Period', 'Typical', '8/ 3', '8/ 9', 'Winter - Week Nearest Min Temperature For Period', 'Extreme', '1/13', '1/19', 'Winter - Week Nearest Average Temperature For Period', 'Typical', '2/17', '2/23', 'Autumn - Week Nearest Average Temperature For Period', 'Typical', '10/27', '11/ 2', 'Spring - Week Nearest Average Temperature For Period', 'Typical', '3/29', '4/ 4'], 'GROUND TEMPERATURES': ['3', '.5', '', '', '', '-2.98', '-1.17', '2.35', '5.68', '11.99', '15.31', '16.23', '14.55', '10.66', '5.81', '1.03', '-2.12', '2', '', '', '', '-0.49', '-0.04', '1.96', '4.20', '9.05', '12.15', '13.69', '13.34', '11.13', '7.78', '4.01', '1.05', '4', '', '', '', '2.09', '1.78', '2.66', '3.93', '7.13', '9.53', '11.09', '11.47', '10.50', '8.53', '5.97', '3.66'], 'HOLIDAYS/DAYLIGHT SAVINGS': ['No', '0', '0', '0'], 'COMMENTS 1': ["IWEC- WMO#014880 - Europe -- Original Source Data (c) 2001 American Society of Heating, Refrigerating and Air-Conditioning Engineers (ASHRAE), Inc., Atlanta, GA, USA.  www.ashrae.org  All rights reserved as noted in the License Agreement and Additional Conditions. DISCLAIMER OF WARRANTIES: The data is provided 'as is' without warranty of any kind, either expressed or implied. The entire risk as to the quality and performance of the data is with you. In no event will ASHRAE or its contractors be liable to you for any damages, including without limitation any lost profits, lost savings, or other incidental or consequential damages arising out of the use or inability to use this data."], 'COMMENTS 2': [' -- Ground temps produced with a standard soil diffusivity of 2.3225760E-03 {m**2/day}'], 'DATA PERIODS': ['1', '1', 'Data', 'Sunday', ' 1/ 1', '12/31']}

In [10]:
df=data.dataframe.copy()  # this is pandas dataframe

In [11]:
df.columns

Index(['Year', 'Month', 'Day', 'Hour', 'Minute',
       'Data Source and Uncertainty Flags', 'Dry Bulb Temperature',
       'Dew Point Temperature', 'Relative Humidity',
       'Atmospheric Station Pressure', 'Extraterrestrial Horizontal Radiation',
       'Extraterrestrial Direct Normal Radiation',
       'Horizontal Infrared Radiation Intensity',
       'Global Horizontal Radiation', 'Direct Normal Radiation',
       'Diffuse Horizontal Radiation', 'Global Horizontal Illuminance',
       'Direct Normal Illuminance', 'Diffuse Horizontal Illuminance',
       'Zenith Luminance', 'Wind Direction', 'Wind Speed', 'Total Sky Cover',
       'Opaque Sky Cover (used if Horizontal IR Intensity missing)',
       'Visibility', 'Ceiling Height', 'Present Weather Observation',
       'Present Weather Codes', 'Precipitable Water', 'Aerosol Optical Depth',
       'Snow Depth', 'Days Since Last Snowfall', 'Albedo',
       'Liquid Precipitation Depth', 'Liquid Precipitation Quantity'],
      dtype='object')

In [12]:
meteo.columns

Index(['Temperature_C', 'Dew_Point_C', 'Humidity', 'Wind', 'Speed_m/s',
       'Gust_m/s', 'Pressure_Pa', 'Precip_Rate_mm', 'Precip_Accum_mm', 'UV',
       'Solar_W/m2'],
      dtype='object')

In [13]:
#df.drop(df.tail(1).index,inplace=True) # drop last n rows
#df

In [14]:
df['Year'] = 2019
df

,Year,Month,Day,Hour,Minute,Data Source and Uncertainty Flags,Dry Bulb Temperature,Dew Point Temperature,Relative Humidity,Atmospheric Station Pressure,...,Ceiling Height,Present Weather Observation,Present Weather Codes,Precipitable Water,Aerosol Optical Depth,Snow Depth,Days Since Last Snowfall,Albedo,Liquid Precipitation Depth,Liquid Precipitation Quantity
0,2019,1,1,1,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,-10.6,-11.9,89,100600,...,77777,9,999999999,0,0.030,0,88,0.0,0.0,0.0
1,2019,1,1,2,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,-8.4,-9.6,90,100500,...,77777,9,999999999,0,0.030,0,88,0.0,0.0,0.0
2,2019,1,1,3,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,-6.8,-7.9,91,100400,...,77777,9,999999999,0,0.030,0,88,0.0,0.0,0.0
3,2019,1,1,4,60,C9C9C9C9*0?9?9?9?9?9?9?9A7A7A7A7A7A7*0E8*0*0,-6.0,-7.0,92,100400,...,240,0,999099999,0,0.030,0,88,0.0,0.0,0.0
4,2019,1,1,5,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,-5.6,-6.5,93,100400,...,240,9,999999999,0,0.030,0,88,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2019,12,31,20,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,-16.5,-18.4,84,100900,...,22000,9,999999999,0,0.032,34,88,0.0,0.0,0.0
8756,2019,12,31,21,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,-16.6,-18.4,84,100900,...,22000,9,999999999,0,0.032,34,88,0.0,0.0,0.0
8757,2019,12,31,22,60,C9C9C9C9*0?9?9?9?9?9?9?9A7A7A7A7A7A7*0E8*0*0,-16.2,-18.0,85,100900,...,22000,9,999999999,0,0.032,34,88,0.0,0.0,0.0
8758,2019,12,31,23,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,-15.0,-16.6,86,100800,...,22000,9,999999999,0,0.032,34,88,0.0,0.0,0.0
8759,2019,12,31,24,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,-13.0,-14.4,88,100700,...,22000,9,999999999,0,0.032,34,88,0.0,0.0,0.0

In [15]:
df['Dry Bulb Temperature']= meteo.Temperature_C.values

In [16]:
df['Dew Point Temperature']=meteo.Dew_Point_C.values

In [17]:
#df['Atmospheric Station Pressure']=meteo.Pressure_Pa

In [18]:
df['Relative Humidity']=meteo.Humidity.values

In [19]:
df['Global Horizontal Radiation']=rad.ghi.values

In [20]:
df['Direct Normal Radiation']=rad.dni.values

In [21]:
df['Diffuse Horizontal Radiation']=rad.dhi.values

In [22]:
df['Wind Direction']=meteo['Speed_m/s'].values

In [23]:
df['Wind Speed']=meteo['Speed_m/s'].values

In [24]:
df.head()

,Year,Month,Day,Hour,Minute,Data Source and Uncertainty Flags,Dry Bulb Temperature,Dew Point Temperature,Relative Humidity,Atmospheric Station Pressure,...,Ceiling Height,Present Weather Observation,Present Weather Codes,Precipitable Water,Aerosol Optical Depth,Snow Depth,Days Since Last Snowfall,Albedo,Liquid Precipitation Depth,Liquid Precipitation Quantity
0,2019,1,1,1,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,5.657407,3.648148,87.500000,100600,...,77777,9,999999999,0,0.03,0,88,0.0,0.0,0.0
1,2019,1,1,2,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,6.416667,1.398148,70.333333,100500,...,77777,9,999999999,0,0.03,0,88,0.0,0.0,0.0
2,2019,1,1,3,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,5.898148,-0.990741,61.333333,100400,...,77777,9,999999999,0,0.03,0,88,0.0,0.0,0.0
3,2019,1,1,4,60,C9C9C9C9*0?9?9?9?9?9?9?9A7A7A7A7A7A7*0E8*0*0,5.620370,-3.703704,51.166667,100400,...,240,0,999099999,0,0.03,0,88,0.0,0.0,0.0
4,2019,1,1,5,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,5.231481,-3.009259,55.333333,100400,...,240,9,999999999,0,0.03,0,88,0.0,0.0,0.0

In [25]:
data.dataframe.head()

,Year,Month,Day,Hour,Minute,Data Source and Uncertainty Flags,Dry Bulb Temperature,Dew Point Temperature,Relative Humidity,Atmospheric Station Pressure,...,Ceiling Height,Present Weather Observation,Present Weather Codes,Precipitable Water,Aerosol Optical Depth,Snow Depth,Days Since Last Snowfall,Albedo,Liquid Precipitation Depth,Liquid Precipitation Quantity
0,1991,1,1,1,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,-10.6,-11.9,89,100600,...,77777,9,999999999,0,0.03,0,88,0.0,0.0,0.0
1,1991,1,1,2,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,-8.4,-9.6,90,100500,...,77777,9,999999999,0,0.03,0,88,0.0,0.0,0.0
2,1991,1,1,3,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,-6.8,-7.9,91,100400,...,77777,9,999999999,0,0.03,0,88,0.0,0.0,0.0
3,1991,1,1,4,60,C9C9C9C9*0?9?9?9?9?9?9?9A7A7A7A7A7A7*0E8*0*0,-6.0,-7.0,92,100400,...,240,0,999099999,0,0.03,0,88,0.0,0.0,0.0
4,1991,1,1,5,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,-5.6,-6.5,93,100400,...,240,9,999999999,0,0.03,0,88,0.0,0.0,0.0

In [26]:
data.dataframe=df.copy()

In [27]:
data.headers['LOCATION']

['OSLO/FORNEBU',
 '-',
 'NOR',
 'IWEC Data',
 '014880',
 '59.90',
 '10.62',
 '1.0',
 '17.0']

In [28]:
data.write('final_2019_oslo.epw')

In [29]:
data.dataframe

,Year,Month,Day,Hour,Minute,Data Source and Uncertainty Flags,Dry Bulb Temperature,Dew Point Temperature,Relative Humidity,Atmospheric Station Pressure,...,Ceiling Height,Present Weather Observation,Present Weather Codes,Precipitable Water,Aerosol Optical Depth,Snow Depth,Days Since Last Snowfall,Albedo,Liquid Precipitation Depth,Liquid Precipitation Quantity
0,2019,1,1,1,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,5.657407,3.648148,87.500000,100600,...,77777,9,999999999,0,0.030,0,88,0.0,0.0,0.0
1,2019,1,1,2,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,6.416667,1.398148,70.333333,100500,...,77777,9,999999999,0,0.030,0,88,0.0,0.0,0.0
2,2019,1,1,3,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,5.898148,-0.990741,61.333333,100400,...,77777,9,999999999,0,0.030,0,88,0.0,0.0,0.0
3,2019,1,1,4,60,C9C9C9C9*0?9?9?9?9?9?9?9A7A7A7A7A7A7*0E8*0*0,5.620370,-3.703704,51.166667,100400,...,240,0,999099999,0,0.030,0,88,0.0,0.0,0.0
4,2019,1,1,5,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,5.231481,-3.009259,55.333333,100400,...,240,9,999999999,0,0.030,0,88,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2019,12,31,20,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,3.120370,-9.916667,37.833333,100900,...,22000,9,999999999,0,0.032,34,88,0.0,0.0,0.0
8756,2019,12,31,21,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,2.981481,-9.768519,38.666667,100900,...,22000,9,999999999,0,0.032,34,88,0.0,0.0,0.0
8757,2019,12,31,22,60,C9C9C9C9*0?9?9?9?9?9?9?9A7A7A7A7A7A7*0E8*0*0,2.703704,-9.574074,40.000000,100900,...,22000,9,999999999,0,0.032,34,88,0.0,0.0,0.0
8758,2019,12,31,23,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,3.333333,-9.222222,39.333333,100800,...,22000,9,999999999,0,0.032,34,88,0.0,0.0,0.0
8759,2019,12,31,24,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,2.814815,-9.305556,40.500000,100700,...,22000,9,999999999,0,0.032,34,88,0.0,0.0,0.0